Refactor: generalize walk through value progress
This commit introduce walkValue() to do the job of calling walk().

TODO: Fix the non-ordered map bug
Because the map key is non-ordered, so if you run test for several
times:

$ go test -v --run "TestWalk/Maps"

You will get:

=== RUN   TestWalk
=== RUN   TestWalk/Maps
    reflection_test.go:98: got [Boz Bar], want [Bar Boz]
--- FAIL: TestWalk (0.00s)
    --- FAIL: TestWalk/Maps (0.00s)
FAIL
exit status 1
FAIL	_/Users/tacomaker/repo/sandbox/go/Learn-go-with-tests/reflection	0.009s