Implement ploting data mechanism for isascii
TODO: fix the bug below:

$ make plotisascii
./isascii > plot/out.txt
python3 scripts/plot.py
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
Traceback (most recent call last):
  File "scripts/plot.py", line 4, in <module>
    data = np.loadtxt("../plot/out.txt")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 533, in open
    encoding=encoding, newline=newline)
FileNotFoundError: [Errno 2] No such file or directory: '../plot/out.txt'
Makefile:14: recipe for target 'plotisascii' failed
make: *** [plotisascii] Error 1