Upgrade rsc.io/sampler pkg to v1.3.1
This commit try to experiment with incomparable ver. of deps.

- Try: rsc.io/sampler@v1.99.99

$ go get rsc.io/sampler

In go.mod

rsc.io/sampler v1.99.99 // indirect

Will be added.

And the test will fail:

=== RUN   TestHello
    hello_test.go:8: Hello() = "99 bottles of beer on the wall, 99 bottles of beer, ...", want "Hello, world."
--- FAIL: TestHello (0.00s)
FAIL
exit status 1
FAIL	example.com/hello	0.007s

- Downgrade to 1.3.1

$ go get rsc.io/sampler@v1.3.1

In go.mod

The deps changed to v1.3.1

rsc.io/sampler v1.3.1 // indirect

The test passed.

Ref: [The Go Blog - Using Go Modules: Upgrading dependencies](https://blog.golang.org/using-go-modules)